name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild clean build -project 'Atom Attack.xcodeproj' -scheme 'Atom Attack' -sdk iphonesimulator
